export interface AdminImageDto {
  Url?: string;
  url?: string;
  Id?: number;
  id?: number;
}

export interface ContactInfoDto {
  name?: string;
  Name?: string;
  phone?: string;
  Phone?: string;
}

export interface InstallmentDto {
  paymentType?: string;
  PaymentType?: string;
  discountPercent?: number;
  DiscountPercent?: number;
  downPaymentPercent?: number;
  DownPaymentPercent?: number;
  years?: number;
  Years?: number;
  isEnabled?: boolean;
  IsEnabled?: boolean;
}

export interface VideoDto {
  id: number;
  url: string;
  publicId?: string;
  thumbnailUrl?: string;
}

export interface PropertyDto {
  id: number;
  publicKey?: string;
  code?: string;
  propertyCode?: string;
  titleEn?: string;
  title?: string;
  titleAr?: string;
  descriptionEn?: string;
  description?: string;
  descriptionAr?: string;
  price: number;
  rentPerMonth?: number;
  currency?: string;
  location: string;
  locationAr?: string;
  type?: string;
  propertyType?: string;
  listingType: string;
  size: number;
  bedrooms?: number;
  bathrooms?: number;
  floor?: number;
  totalFloors?: number;
  isFurnished?: boolean;
  view?: string;
  unitNumber?: string;
  buildingNumber?: string;
  deliveryDate?: string;
  finishingType?: string;
  hasBalcony?: boolean;
  hasParking?: boolean;
  features: string[];
  featuresAr?: string[];
  installments?: InstallmentDto[];
  Installments?: InstallmentDto[];
  contactId?: number;
  contactName?: string;
  contactPhone?: string;
  contact?: { name: string; phone: string; type: string };
  projectId?: number;
  projectName?: string;
  images: string[];
  image?: string;
  isFeatured: boolean;
  isRecommended?: boolean;
  slug: string;
  slugIsAuto: boolean;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: string;
  seoTitleAr?: string;
  seoDescriptionAr?: string;
  seoKeywordsAr?: string;
  canonicalUrl?: string;
  deliveryText?: string;
  deliveryTextAr?: string;
  constructionStatus?: string;
  availabilityStatus?: string;
  ownershipType?: string;
  viewCount?: number;
  inquiryCount?: number;
  favoriteCount?: number;
  virtualTourUrl?: string;
  highlightsAr?: string[];
  nearbyPlaces?: string[];
  nearbyPlacesAr?: string[];
  createdAt: string;
  order: number;
  videos?: VideoDto[];
  adminImages?: AdminImageDto[];
  AdminImages?: AdminImageDto[];
  contactInfo?: ContactInfoDto;
  ContactInfo?: ContactInfoDto;
}

export interface ProjectDto {
  id: number;
  publicKey?: string;
  nameEn: string;
  name?: string;
  nameAr?: string;
  slug: string;
  location: string;
  locationAr?: string;
  developer: string;
  unitCount: number;
  descriptionEn?: string;
  description?: string;
  descriptionAr?: string;
  image: string;
  highlights: string[];
  highlightsAr?: string[];
  startingPrice?: number;
  nearbyPlaces?: string[];
  propertyTypes?: string[];
  latitude?: number;
  longitude?: number;
  totalArea?: number;
  ownershipType?: string;
  order: number;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: string;
  seoTitleAr?: string;
  seoDescriptionAr?: string;
  seoKeywordsAr?: string;
  videos?: VideoDto[];
  deliveryText?: string;
  deliveryTextAr?: string;
  isRecommended?: boolean;
  constructionStatus?: string;
  availabilityStatus?: string;
  viewCount?: number;
  inquiryCount?: number;
  favoriteCount?: number;
  virtualTourUrl?: string;
  nearbyPlacesAr?: string[];
}

export interface UnitDto {
  id: number;
  publicKey?: string;
  code?: string;
  titleEn?: string;
  title?: string;
  titleAr?: string;
  descriptionEn?: string;
  description?: string;
  descriptionAr?: string;
  price: number;
  rentPerMonth?: number;
  currency?: string;
  location: string;
  locationAr?: string;
  type?: string;
  propertyType?: string;
  listingType: string;
  size: number;
  bedrooms?: number;
  bathrooms?: number;
  floor?: number;
  isFurnished?: boolean;
  view?: string;
  unitNumber?: string;
  buildingNumber?: string;
  deliveryDate?: string;
  finishingType?: string;
  hasBalcony?: boolean;
  hasParking?: boolean;
  features: string[];
  featuresAr?: string[];
  installments?: InstallmentDto[];
  Installments?: InstallmentDto[];
  contactInfo?: ContactInfoDto;
  ContactInfo?: ContactInfoDto;
  contactId?: number;
  projectId?: number;
  images: string[];
  image?: string;
  isFeatured: boolean;
  isRecommended?: boolean;
  slug: string;
  slugIsAuto: boolean;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: string;
  seoTitleAr?: string;
  seoDescriptionAr?: string;
  seoKeywordsAr?: string;
  deliveryText?: string;
  deliveryTextAr?: string;
  constructionStatus?: string;
  availabilityStatus?: string;
  ownershipType?: string;
  viewCount?: number;
  inquiryCount?: number;
  favoriteCount?: number;
  virtualTourUrl?: string;
  highlightsAr?: string[];
  nearbyPlaces?: string[];
  nearbyPlacesAr?: string[];
  createdAt: string;
  order: number;
  variants?: UnitVariantDto[];
  adminImages?: AdminImageDto[];
  AdminImages?: AdminImageDto[];
}

export interface CreatePropertyPayload {
  titleEn: string;
  titleAr?: string;
  descriptionEn?: string;
  descriptionAr?: string;
  price: number;
  rentPerMonth?: number | null;
  location: string;
  locationAr?: string;
  size: number;
  bedrooms?: number | null;
  bathrooms?: number | null;
  floor?: number | null;
  totalFloors?: number | null;
  isFurnished?: boolean;
  view?: string | null;
  propertyType: string;
  listingType: string;
  contact?: { name: string; phone: string; type: number } | null;
  contactId?: string;
  contactName?: string;
  contactPhone?: string;
  images?: string[];
  features?: string[];
  featuresAr?: string[];
  installments?: { paymentType: string; downPaymentPercent: number; discountPercent: number; years: number; isEnabled: boolean }[];
  slug?: string;
  slugIsAuto?: boolean;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoKeywords?: string | null;
  seoTitleAr?: string | null;
  seoDescriptionAr?: string | null;
  seoKeywordsAr?: string | null;
  sortOrder?: number;
  isRecommended?: boolean;
  deliveryText?: string | null;
  deliveryTextAr?: string | null;
  constructionStatus?: string | null;
  availabilityStatus?: string | null;
  ownershipType?: string | null;
  virtualTourUrl?: string | null;
  highlightsAr?: string[];
  nearbyPlaces?: string[];
  nearbyPlacesAr?: string[];
}

export interface CreateUnitVariantDto {
  name?: string;
  size?: number;
  price?: number;
  currency?: string;
  rentPerMonth?: number;
  images?: string[];
  bedrooms?: number;
  bathrooms?: number;
  floor?: number;
  isFurnished?: boolean;
  view?: string;
  unitNumber?: string;
  buildingNumber?: string;
  deliveryDate?: string;
  finishingType?: string;
  hasBalcony?: boolean;
  hasParking?: boolean;
  floorPlanUrl?: string;
  availabilityStatus?: string;
  isFeatured?: boolean;
  isRecommended?: boolean;
  deliveryText?: string;
  deliveryTextAr?: string;
  sortOrder?: number;
  isActive?: boolean;
}

export interface UnitVariantDto {
  id: number;
  unitId: number;
  name?: string;
  size?: number;
  price?: number;
  currency?: string;
  rentPerMonth?: number;
  images?: string[];
  bedrooms?: number;
  bathrooms?: number;
  floor?: number;
  isFurnished?: boolean;
  view?: string;
  unitNumber?: string;
  buildingNumber?: string;
  deliveryDate?: string;
  finishingType?: string;
  hasBalcony?: boolean;
  hasParking?: boolean;
  floorPlanUrl?: string;
  availabilityStatus?: string;
  isFeatured?: boolean;
  isRecommended?: boolean;
  viewCount?: number;
  inquiryCount?: number;
  favoriteCount?: number;
  deliveryText?: string;
  deliveryTextAr?: string;
  sortOrder?: number;
  isActive?: boolean;
}

export interface CreateUnitPayload {
  titleEn: string;
  titleAr?: string;
  descriptionEn?: string;
  descriptionAr?: string;
  minPrice?: number;
  maxPrice?: number;
  rentPerMonth?: number | null;
  location: string;
  locationAr?: string;
  minArea?: number;
  maxArea?: number;
  bedrooms?: number | null;
  bathrooms?: number | null;
  floor?: number | null;
  isFurnished?: boolean;
  view?: string | null;
  unitNumber?: string;
  buildingNumber?: string;
  deliveryDate?: string | null;
  finishingType?: string | null;
  hasBalcony?: boolean;
  hasParking?: boolean;
  propertyType: string;
  listingType: string;
  projectId?: number;
  contact?: { name: string; phone: string; type: number } | null;
  features?: string[];
  featuresAr?: string[];
  installments?: { paymentType: string; downPaymentPercent: number; discountPercent: number; years: number; isEnabled: boolean }[];
  variants?: CreateUnitVariantDto[];
  slug?: string;
  slugIsAuto?: boolean;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoKeywords?: string | null;
  seoTitleAr?: string | null;
  seoDescriptionAr?: string | null;
  seoKeywordsAr?: string | null;
  order?: number;
  isRecommended?: boolean;
  deliveryText?: string | null;
  deliveryTextAr?: string | null;
  constructionStatus?: string | null;
  availabilityStatus?: string | null;
  ownershipType?: string | null;
  virtualTourUrl?: string | null;
  highlightsAr?: string[];
  nearbyPlaces?: string[];
  nearbyPlacesAr?: string[];
}

export interface CreateProjectPayload {
  nameEn: string;
  nameAr: string;
  descriptionEn: string;
  descriptionAr: string;
  location: string;
  locationAr?: string;
  developer: string;
  image?: string;
  highlights?: string[];
  highlightsAr?: string[];
  startingPrice?: number;
  nearbyPlaces?: string[];
  nearbyPlacesAr?: string[];
  propertyTypes?: string[];
  latitude?: number;
  longitude?: number;
  totalArea?: number;
  ownershipType?: string;
  unitCount?: number;
  deliveryText?: string;
  deliveryTextAr?: string;
  isRecommended?: boolean;
  constructionStatus?: string;
  availabilityStatus?: string;
  viewCount?: number;
  inquiryCount?: number;
  favoriteCount?: number;
  virtualTourUrl?: string;
  slug?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: string;
  seoTitleAr?: string;
  seoDescriptionAr?: string;
  seoKeywordsAr?: string;
}

export interface DashboardStatsDto {
  totalProperties: number;
  totalProjects: number;
  rentalProperties: number;
  resaleProperties: number;
  projectUnits: number;
  totalLeads: number;
  totalBookings: number;
  totalLandRequests: number;
  featuredProperties?: number;
}

export interface VisitHistoryEntry {
  timestamp: string;
  path: string;
  title?: string;
}
